CREATE TABLE IF NOT EXISTS vehicledata (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	idTrip INTEGER,
	idVehicle TEXT,
	route TEXT,
	timestamp NUMBER,
	speed NUMBER,
	accX NUMBER,
	accY NUMBER,
	accZ NUMBER,
	velAngX NUMBER,
	velAngY NUMBER,
	velAngZ NUMBER,
	magX NUMBER,
	magY NUMBER,
	magZ NUMBER,
	latitude NUMBER,
	longitude NUMBER,
	accPosition NUMBER,
	eventClass BOOLEAN,
	active BOOLEAN
);
